project_id = "social"

[auth]
additional_redirect_urls = ["env(SUPABASE_AUTH_REDIRECT_URI)"]

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = "env(SUPABASE_AUTH_PROVIDER_REDIRECT_URI)"
